-- AUTOMATICALLY GENERATED BY scripts/GetHooks.py! DO NOT MODIFY! --


-- defined in indra/newview/llfloaterbump.cpp:164
RegisterHook("OnBump", "You were bumped by something")

-- defined in indra/newview/llviewermessage.cpp:2626
RegisterHook("OnChatDebug", "Triggered when an object states something on the debug channel.")

-- defined in indra/newview/llagent.cpp:937
RegisterHook("OnRegionChanged", "Tells Lua that you have moved into a new region.")

-- defined in indra/newview/llviewerwindow.cpp:799
RegisterHook("OnLeftMouseUp", "Left mouse button is UP.")

-- defined in indra/newview/llvoavatar.cpp:3089
RegisterHook("OnAvatarLoading", "Trigger loading effect plugin :V")

-- defined in indra/newview/llviewermessage.cpp:2644
RegisterHook("OnChatUnknown", "Triggered when someone uses an unknown chat method.")

-- defined in indra/newview/llviewerobjectlist.cpp:1374
RegisterHook("OnObjectCreated", "An object has rezzed/appeared.")

-- defined in indra/newview/llviewerwindow.cpp:1099
RegisterHook("OnMiddleMouseDown", "Middle mouse button is Down.")

-- defined in indra/newview/llviewerobject.cpp:4287
RegisterHook("OnAttachedParticles", "Particle data.")

-- defined in indra/newview/llviewerwindow.cpp:1255
RegisterHook("OnKeyDown", "Right mouse button is DOWN.")

-- defined in indra/newview/llvoavatar.cpp:5546
RegisterHook("OnAnimStop", "For AOs.")

-- defined in indra/newview/llviewerobject.cpp:4413
RegisterHook("OnAttachedSound", "Object playing a sound (includes looped sounds).")

-- defined in indra/newview/llvoavatar.cpp:5479
RegisterHook("OnAnimStart", "For AOs.")

-- defined in indra/newview/LunaLua.cpp:189
RegisterHook("OnLunaInit", "Luna's Lua engine has initialized.")

-- defined in indra/newview/llviewerwindow.cpp:714
RegisterHook("OnDoubleClick", "Right mouse button is DOWN.")

-- defined in indra/newview/llviewermessage.cpp:2606
RegisterHook("OnChatWhisper", "Triggered when someone whispers something in local chat")

-- defined in indra/newview/llviewerwindow.cpp:2352
RegisterHook("PostUIDraw", "Do GL stuff before drawing the UI. (BLOCKING)")

-- defined in indra/newview/llagent.cpp:478
RegisterHook("OnAgentInit", "On login, tells the Lua engine the name of the user and whether it's a Linden or not.")

-- defined in indra/newview/llviewerwindow.cpp:1007
RegisterHook("OnRightMouseUp", "Right mouse button is UP.")

-- defined in indra/newview/LuaInventory_f.cpp:231
RegisterHook("OnAssetDownloaded", "Asset successfully downloaded.")

-- defined in indra/newview/llviewerwindow.cpp:1188
RegisterHook("OnWindowResized", "Window was resized.")

-- defined in indra/newview/llviewermessage.cpp:2621
RegisterHook("OnChatSay", "Triggered when an object uses llOwnerSay.")

-- defined in indra/newview/LuaInventory_f.cpp:237
RegisterHook("OnAssetFailed", "Asset failed to download or decode.")

-- defined in indra/newview/llviewerwindow.cpp:895
RegisterHook("OnRightMouseDown", "Right mouse button is DOWN.")

-- defined in indra/newview/llviewermessage.cpp:3692
RegisterHook("OnSoundTriggered", "Triggered when a sound is triggered.")

-- defined in indra/newview/llvoavatar.cpp:3084
RegisterHook("OnAvatarLoaded", "Triggered when an avatar has been fully loaded.")

-- defined in indra/newview/llviewerobject.cpp:1026
RegisterHook("OnSetText", "Someone set this object's llSetText.")

-- defined in indra/newview/llagent.cpp:813
RegisterHook("OnPhantom", "Tells the script engine whether a user has become phantom.")

-- defined in indra/newview/llviewermessage.cpp:2636
RegisterHook("OnChatShout", "Triggered when someone shouts something in local chat.")

-- defined in indra/newview/llviewerwindow.cpp:605
RegisterHook("OnLeftMouseDown", "Left mouse button is DOWN.")

-- defined in indra/newview/llvoavatar.cpp:6713
RegisterHook("OnAttach", "Object UUID has attached to avatar Name.")

-- defined in indra/newview/llviewermessage.cpp:2615
RegisterHook("OnBridgeCommand", "Triggered when an object tries to communicate via the debug channel or the llOwnerSay channel using a command prefixed with &FLEXLIFE;")

-- defined in indra/newview/llviewerwindow.cpp:1112
RegisterHook("OnMiddleMouseUp", "Middle mouse button is Up.")
